            - name: Upload Status Badge
  # You may pin to the exact commit or the version.
  # uses: colinparsonscom/upload-status-badge@a4f435143cc30b6e2fcd485326665fac90d98ae9
  uses: colinparsonscom/upload-status-badge@v0.1.8
  with:
    # A GitHub token with gist scope.
    auth: 
    # The ID of the gist to which to upload the status badge.
    gist-id: 
    # The label of the status badge.
    badge-label: 
    # Either "success" or "failure", indicating what the status badge should display.
    outcome: # optional
    # A fraction, percentage, float, or mathematical expression indicating the number or proportion of passing results (ex: "4/7", "35%", "3.14", or "(2 ^ 4 - 6e-2)/(4 * 2 + 3.2%)").
    passing-results: # optional
    # A strictly increasing list of at most 5 thresholds, separated by commas, and provided as fractions, percentages, floats, or mathematical expressions. At each of these, the badge will display a different color (ex: "0.2, 1/2, 70%" will display red for passing-results up to 0.2, orange for passing-results between 0.2 and 0.5, yellow for passing-results between 0.5 and 0.7, and brightgreen for passing-results above 0.7). If no list is provided, the default thresholds are 0.5 and 0.9 (that is, red for passing-results below 0.5, yellow for passing-results between 0.5 and 0.9, and brightgreen for passing-results above 0.9).
    passing-results-thresholds: # optional, default is 0.5, 0.9
    # Display this custom message instead of success, failure, or number/proportion of passing results (ex: "generally doing OK").
    custom-message: # optional
    # Display this color with a custom message (ex: "a020f0" or "purple").
    custom-color: # optional
          
